on:
  pull_request:
    branches:
      - release  # 'release' 브랜치로 PR이 생성될 때만 실행

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
      ACCESS_EXP: ${{ secrets.ACCESS_EXP }}
      REFRESH_EXP: ${{ secrets.REFRESH_EXP }}
      ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      BUCKET: ${{ secrets.BUCKET }}
      PROFILE_URL: ${{ secrets.PROFILE_URL }}

    services:
      redis:
        image: redis
        ports:
          - 6379:6379

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Cache Gradle dependencies
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Run Spring Boot App for 30 seconds
        run: |
          export SPRING_PROFILES_ACTIVE=test
          ./gradlew bootRun &
          APP_PID=$!
          sleep 30
          kill $APP_PID
        continue-on-error: false

      - name: Build and Test
        run: ./gradlew clean build

